# Generated by Django 3.2.6 on 2021-08-12 10:51

import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210812_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), store.models.max_value_current_year]),
        ),
    ]
